<a href="https://colab.research.google.com/github/hemanthg11/generative-ai-for-beginners/blob/main/Tensorflow_exercises_from_upGrad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

# create nd array in numpy
arr_nm = np.random.randn(2,2,2,2)
arr_nm

arr_tf = tf.constant(arr_nm)
print("Before changing mean & sd: ", arr_tf)
arr_tf = arr_tf * 2 + 1
print("After changing mean & sd: ", arr_tf)

Before changing mean & sd:  tf.Tensor(
[[[[-0.5615051  -0.2326495 ]
   [ 0.27721112  0.36076089]]

  [[ 1.7438801  -1.48454374]
   [ 0.15713659  0.08403558]]]


 [[[ 0.62992475 -1.18302893]
   [ 0.70332983 -0.19006275]]

  [[-0.25713576  0.35287939]
   [ 0.47877209 -0.80558992]]]], shape=(2, 2, 2, 2), dtype=float64)
After changing mean & sd:  tf.Tensor(
[[[[-0.12301019  0.53470101]
   [ 1.55442224  1.72152178]]

  [[ 4.4877602  -1.96908748]
   [ 1.31427318  1.16807116]]]


 [[[ 2.25984951 -1.36605785]
   [ 2.40665967  0.61987449]]

  [[ 0.48572849  1.70575877]
   [ 1.95754419 -0.61117983]]]], shape=(2, 2, 2, 2), dtype=float64)


In [5]:
# Example for squaring a tensor
import tensorflow as tf
import numpy as np

tensor1 = tf.random.uniform((2,2), minval = 1, maxval = 20, dtype = tf.int32)
print("Initial tensor: ", tensor1.numpy())
# tensor2 = tf.pow(tensor1, 2)
# tensor2 = tensor1 * tensor1
tensor2 = tf.multiply(tensor1, tensor1)
print("Squared tensor: ", tensor2.numpy())

Initial tensor:  [[3 3]
 [1 1]]
Squared tensor:  [[9 9]
 [1 1]]


In [6]:
# Example for throwing error due to unequal dimensions
import tensorflow as tf
import numpy as np

t1 = tf.Variable([[2,3,4], [5,7,9], [1,6,3], [5,8,4]])
t2 = tf.Variable([[2,3,4,5], [5,7,9,4], [1,6,3,9]])

t3 = t1 + t2

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [4,3] vs. [3,4] [Op:AddV2] name: 