In [ ]:
# Example for sampling from a Normal distribution
import tensorflow as tf
import numpy as np

# create nd array in numpy
arr_nm = np.random.randn(2,2,2,2)
arr_nm

arr_tf = tf.constant(arr_nm)
print("Before changing mean & sd: ", arr_tf)
arr_tf = arr_tf * 2 + 1
print("After changing mean & sd: ", arr_tf)

Before changing mean & sd:  tf.Tensor(
[[[[-0.5615051  -0.2326495 ]
   [ 0.27721112  0.36076089]]

  [[ 1.7438801  -1.48454374]
   [ 0.15713659  0.08403558]]]


 [[[ 0.62992475 -1.18302893]
   [ 0.70332983 -0.19006275]]

  [[-0.25713576  0.35287939]
   [ 0.47877209 -0.80558992]]]], shape=(2, 2, 2, 2), dtype=float64)
After changing mean & sd:  tf.Tensor(
[[[[-0.12301019  0.53470101]
   [ 1.55442224  1.72152178]]

  [[ 4.4877602  -1.96908748]
   [ 1.31427318  1.16807116]]]


 [[[ 2.25984951 -1.36605785]
   [ 2.40665967  0.61987449]]

  [[ 0.48572849  1.70575877]
   [ 1.95754419 -0.61117983]]]], shape=(2, 2, 2, 2), dtype=float64)


In [ ]:
# Example for squaring a tensor
import tensorflow as tf
import numpy as np

tensor1 = tf.random.uniform((2,2), minval = 1, maxval = 20, dtype = tf.int32)
print("Initial tensor: ", tensor1.numpy())
# tensor2 = tf.pow(tensor1, 2)
# tensor2 = tensor1 * tensor1
tensor2 = tf.multiply(tensor1, tensor1)
print("Squared tensor: ", tensor2.numpy())

Initial tensor:  [[3 3]
 [1 1]]
Squared tensor:  [[9 9]
 [1 1]]


In [ ]:
# Example for throwing error due to unequal dimensions
import tensorflow as tf
import numpy as np

t1 = tf.Variable([[2,3,4], [5,7,9], [1,6,3], [5,8,4]])
t2 = tf.Variable([[2,3,4,5], [5,7,9,4], [1,6,3,9]])

t3 = t1 + t2

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [4,3] vs. [3,4] [Op:AddV2] name: 

In [5]:
# Example for matrix multiplication
import tensorflow as tf

x = tf.Variable([[0,1,2,3,4],[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8]])
y = tf.Variable([[0,5,10],[5,10,15],[10,15,20],[15,20,25],[20,25,30]]) # matrix sizes (5 x 5) and (5 x 3) are compatible for multiplication
#y = tf.Variable([[0,5,10],[5,10,15],[10,15,20],[15,20,25]]) # throws exception since matrix sizes (5 x 5) and (4 x 3) are incompatible for multiplication

z = tf.linalg.matmul(x, y)
print("z: ", z)

z:  tf.Tensor(
[[150 200 250]
 [200 275 350]
 [250 350 450]
 [300 425 550]
 [350 500 650]], shape=(5, 3), dtype=int32)


In [15]:
# Example for matrix inverse
import tensorflow as tf

try:
#  x = tf.Variable([[1,2],[2,4]]) # throws exception as datatype should be float or double etc
#  x = tf.Variable([[1,2],[2,4]], dtype = tf.float32) # throws exception as determinant is zero ie. 1 x 4 - 2 x 2 = 0
  x = tf.Variable([[1,2],[4,10]], dtype = tf.float32)
  xdet = tf.linalg.det(x)
  xinv = tf.linalg.inv(x)
  print("Matrix x: \n", x)
  print("\nDeterminant of x: ", xdet)
  print("\nInverse of x: \n", xinv)
except Exception as e:
  print("Exception raised while performing inverse of x:\n", str(e))

Matrix x: 
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.,  2.],
       [ 4., 10.]], dtype=float32)>

Determinant of x:  tf.Tensor(2.0, shape=(), dtype=float32)

Inverse of x: 
 tf.Tensor(
[[ 5.  -1. ]
 [-2.   0.5]], shape=(2, 2), dtype=float32)


In [28]:
# Example of solution for simulaneous linear equation W.X = Y
# x + y + z + w = 13
# 2x + 3y - w = -1
# -3x + 4y + z + 2w = 10
# x + 2y -z + w = 1
# Ans: x=2, y=0, z=6, w=5

import tensorflow as tf

# Initialize coefficient matrix
w = tf.constant([[1, 1, 1, 1], [2, 3, 0, -1], [-3, 4, 1, 2], [1, 2, -1, 1]], dtype=tf.float32)
print("Coefficient matrix W: \n", w)

# Initialize output matrix
y = tf.constant([[13], [-1], [10], [1]], dtype=tf.float32)
print("\nOutput matrix Y: \n", y)

# Do matrix multiplication of inverse of W with Y to get X (solution)
winv = tf.linalg.inv(w)
print("\nInverse of coefficient matrix W: ", winv)
x = tf.linalg.matmul(winv, y)
print("\nSolution matrix X: \n", x)

# Forcing the values to integer data type after rounding
#xint = tf.cast(tf.math.round(x), dtype=tf.int32) # does both rounding and casting to integer
xint = tf.math.round(x) # does only rounding
print("\nSolution matrix X (integer vals): \n", xint)

Coefficient matrix W: 
 tf.Tensor(
[[ 1.  1.  1.  1.]
 [ 2.  3.  0. -1.]
 [-3.  4.  1.  2.]
 [ 1.  2. -1.  1.]], shape=(4, 4), dtype=float32)

Output matrix Y: 
 tf.Tensor(
[[13.]
 [-1.]
 [10.]
 [ 1.]], shape=(4, 1), dtype=float32)

Inverse of coefficient matrix W:  tf.Tensor(
[[ 2.77777791e-01  5.55555224e-02 -1.66666672e-01  1.11111104e-01]
 [-7.40740746e-02  1.85185164e-01  1.11111104e-01  3.70370336e-02]
 [ 4.62962925e-01  9.25926119e-02  5.55555634e-02 -4.81481493e-01]
 [ 3.33333343e-01 -3.33333343e-01 -9.93410776e-09  3.33333343e-01]], shape=(4, 4), dtype=float32)

Solution matrix X: 
 tf.Tensor(
[[ 2.0000000e+00]
 [-1.0058284e-07]
 [ 5.9999995e+00]
 [ 5.0000005e+00]], shape=(4, 1), dtype=float32)

Solution matrix X (integer vals): 
 tf.Tensor(
[[ 2.]
 [-0.]
 [ 6.]
 [ 5.]], shape=(4, 1), dtype=float32)


In [32]:
# upGrad exercise on regression
# W.X + B = Y

import tensorflow as tf

# Initialize coefficient matrix
w = tf.constant([[0.5, 1, -1.2, 0.01]], dtype=tf.float32) # using homogenous coefficients ie. include b in matrix W and use input=1
print("Coefficient matrix W: \n", w)

# Initialize input matrix
x = tf.constant([[0.2], [1], [0.5], [1]], dtype=tf.float32)
print("\nInput matrix X: \n", x)

# Do matrix multiplication of W with X to get Z (cumulative input)
z = tf.linalg.matmul(w, x)
print("\nSolution Y: \n", z)

# Give cumulative output Z to activation function H to get output probability
h = tf.math.sigmoid(z)
print("\nOutput probability H: ", h)

Coefficient matrix W: 
 tf.Tensor([[ 0.5   1.   -1.2   0.01]], shape=(1, 4), dtype=float32)

Input matrix X: 
 tf.Tensor(
[[0.2]
 [1. ]
 [0.5]
 [1. ]], shape=(4, 1), dtype=float32)

Solution Y: 
 tf.Tensor([[0.51]], shape=(1, 1), dtype=float32)

Output probability H:  tf.Tensor([[0.62480646]], shape=(1, 1), dtype=float32)
